### PR TITLE
added opcodes: SHL, SDIV, SMOD

### PR DESCRIPTION
**Pull request by hananbeer**

### CODE REVIEW

**Comment by karmacoma-eth** [comment]
thanks a bunch! I'll take a look at the conflict, someone else picked up SHL

**Comment by beskay** [comment]
I like the way you convert uint > int, I used it for my pull request too, but why did you use `& MAX_UINT256` instead of `% 2**256`?

**Comment by hananbeer** [comment]
> I like the way you convert uint > int, I used it for my pull request too, but why did you use `& MAX_UINT256` instead of `% 2**256`?

force of optimisation habbit. redundant calculation, supposedly faster. I'm not married to it

**Comment by beskay** [comment]
> force of optimisation habbit. redundant calculation, supposedly faster. I'm not married to it

Cool, I didnt know that. Thanks for the info.

**Review by karmacoma-eth — APPROVED** [review]

**Pull request merged**
